[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600
upload_port = COM6
monitor_port = COM6
monitor_rts = 0
monitor_dtr = 0

board_build.partitions = huge_app.csv

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D CORE_DEBUG_LEVEL=5

lib_deps =
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library @ ^1.1.2
    bblanchon/ArduinoJson @ ^7.2.0
    h2zero/NimBLE-Arduino @ ^1.4.2
